/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp9;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author pcast
 */
public class VistaMenu extends javax.swing.JFrame {
   
    Controlador control;
    CardLayout cardlayout;

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
        Modelo modeloControlador = new Modelo();
        control = new Controlador( this, modeloControlador );
      /*  CardLayout cardlayout = new CardLayout();
        cardlayout.addLayoutComponent(Formulario, "Formulario");
        cardlayout.addLayoutComponent(Menu, "Menu");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mostrar2 = new javax.swing.JButton();
        Terminar2 = new javax.swing.JButton();
        Titulo2 = new javax.swing.JLabel();
        Ingresar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");

        Mostrar2.setText("Mostrar Estudiante");
        Mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar2ActionPerformed(evt);
            }
        });

        Terminar2.setText("Terminar");
        Terminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terminar2ActionPerformed(evt);
            }
        });

        Titulo2.setText("Menú Estudiante");

        Ingresar2.setText("Ingresar Estudiante");
        Ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ingresar2)
                            .addComponent(Mostrar2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(Terminar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Titulo2)))
                .addGap(37, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titulo2)
                .addGap(35, 35, 35)
                .addComponent(Ingresar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar2)
                .addGap(18, 18, 18)
                .addComponent(Terminar2)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar2ActionPerformed
        try {
            control.mostrarDato();
        } catch (IOException ex) {
            Logger.getLogger(VistaMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Mostrar2ActionPerformed

    private void Terminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terminar2ActionPerformed
      try {
          System.out.println("--Salir del Menú--");
            control.mostrarDato();
             this.dispose(); 
        } catch (IOException ex) {
            Logger.getLogger(VistaMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Terminar2ActionPerformed

    private void Ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar2ActionPerformed
        Vista formulario = new Vista();
        formulario.setVisible(true);
        formulario.setTitle("Formulario");
        formulario.setLocationRelativeTo(null);
       
        this.setVisible(false);
    }//GEN-LAST:event_Ingresar2ActionPerformed

     public void setEscribirListener(ActionListener listener) {
        //control.formulario(listener);
        //Ingresar.addActionListener(listener);
        
    }
    
    public void setLeerListener(ActionListener listener) {
        //Mostrar.addActionListener(listener);
    }
    
    public void setTerminarListener(ActionListener listener) {
      //  Terminar.addActionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ingresar2;
    public javax.swing.JButton Mostrar2;
    public javax.swing.JButton Terminar2;
    private javax.swing.JLabel Titulo2;
    // End of variables declaration//GEN-END:variables
}
